@startuml
title CONectaSM - UC-07 Capacidades Could Have y evolución futura
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

actor "Usuario" as Usuario
actor "Cliente" as Cliente
actor "Prestador" as Prestador
actor "Gestor comunitario" as Gestor


Usuario <|-- Cliente
Usuario <|-- Prestador

rectangle "CONectaSM - Evolución" {
  usecase "Chat interno en tiempo real\n[US-096] <<Could>>" as UC086
  usecase "Mapa visual de prestadores\n[US-097] <<Could>>" as UC087
  usecase "Insignia de progreso de\nformalización\n[US-098] <<Could>>" as UC088
  usecase "Programa de referidos\n[US-099] <<Could>>" as UC089
  usecase "Soporte por WhatsApp\n[US-100] <<Could>>" as UC090
  usecase "Onboarding asistido por\nWhatsApp o gestor\n[US-101] <<Could>>" as UC091
  usecase "Vincular ruta institucional\nfutura\n[US-088] <<Future>>" as UC080
  usecase "Seleccionar idioma\n[US-102] <<Could>>" as UC092
  usecase "Pagar servicio mediante\npasarela\n[US-103] <<Future>>" as UC093
}

Cliente --> UC086
Prestador --> UC086
Cliente --> UC087
Cliente --> UC088
Prestador --> UC088
Usuario --> UC089
Usuario --> UC090
Prestador --> UC091
Prestador --> UC080
Usuario --> UC092
Cliente --> UC093
Prestador --> UC093


Gestor --> UC091


@enduml
