@startuml
title CONectaSM - UC-03 Prestador: perfil y oportunidades
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

actor "Prestador" as Prestador

rectangle "CONectaSM" {
  usecase "Crear perfil profesional\n[US-014]" as UC024
  usecase "Editar perfil profesional\n[US-015]" as UC025
  usecase "Escoger categorías\nde servicio al perfil\n[US-016]" as UC026
  usecase "Configurar zonas\nde atención\n[US-017]" as UC027
  usecase "Registrar experiencia\nprofesional al perfil \n[US-018]" as UC028
  usecase " Agregar servicio al portafolio\n[US-019]" as UC029
  usecase "Eliminar servicio \nde portafolio\n[US-020]" as UC030
  usecase "Configurar disponibilidad horaria\n[US-021]" as UC031
  usecase "Gestionar agenda \n[US-022]" as UC032
  usecase "Consultar vista previa\ndel perfil\n[US-023]" as UC033

  usecase "Determinar compatibilidad\nde solicitudes\n[US-039]" as UC034
  usecase "Ver tablero de\noportunidades\n[US-040]" as UC035
  usecase "Filtrar oportunidades\n[US-041]" as UC036
  usecase "Consultar detalle\nde oportunidad\n[US-042]" as UC037
  usecase "Notificar nueva oportunidad\ncompatible\n[US-044]" as UC038
}

Prestador --> UC024
Prestador --> UC028
Prestador --> UC025
Prestador --> UC026
Prestador --> UC029
Prestador --> UC030
Prestador --> UC031
Prestador --> UC032
Prestador --> UC033
Prestador --> UC035
Prestador --> UC036
Prestador --> UC037

UC024 .> UC027 : <<include>>
UC024 .> UC026 : <<include>>


UC035 .> UC034 : <<include>>
UC036 .> UC035 : <<extend>>
UC038 .> UC034 : <<extend>>
UC028 .> UC024 : <<extend>>
@enduml
